services:
  postgres:
    image: postgres:16-alpine
    container_name: controle_logistica_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controle_logistica
    volumes:
      - pgdata:/var/lib/postgresql/data

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: controle_logistica_mediamtx
    restart: unless-stopped
    ports:
      - '8554:8554'
      - '8888:8888'
      - '8889:8889'
      - '9997:9997'
    volumes:
      - ./mediamtx.yml:/mediamtx.yml

volumes:
  pgdata:
